name = "CTAF Minecraft Pack"
author = "slimit75"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc4ab2c93186032e4f326e30b15c5d9665b205b7bb4fbb33b39c6a814c4e1063"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
