name = "CTAF Minecraft Pack"
author = "slimit75"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c46d341e58a4d925d4ed7c2ef2a97b8241fd830e5f30da33a9da3eb11807350"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
